#!/bin/sh

#  MOTD Introduction - An MOTD that displays the contents of motd.artemis.org.uk/00

#  Author: Dannington <git@bean.codes>
#  Licence: GNU GPL v2 (utilises version 3)
#  Uses parts of code from other update-motd.d files, (C) Dustin Kirkland <kirkland@canonical.com>

# Set variables for the MOTD
URL="https://motd.artemis.org.uk/00"
WAIT=5
CACHE="/var/cache/motd-news.d/00"
[ "$1" = "--force" ] && FORCED=1

# Safely print the MOTD
safe_print() {
        cat "$1" | head -n 10 | tr -d '\000-\011\013\014\016-\037' | cut -c -80
}

# Set variables for temporary dirs
NEWS=$(mktemp) || exit 1
ERR=$(mktemp) || exit 1

if curl --connect-timeout "$WAIT" --max-time "$WAIT" -Lo- "$URL" >"$NEWS" 2>"$ERR"; then
        echo
        safe_print "$NEWS"
        safe_print "$NEWS" 2>/dev/null >$CACHE || true
else
        : > "$CACHE"
fi
rm -f "$NEWS" "$ERR"
exit 0