#!/bin/sh

#  MOTD News - A dynamic MOTD news component for non-login shells (from motd.artemis.org.uk/50)
#  Author: Dannington <git@bean.codes>
#  Licence: GNU GPL v2 (utilises version 3)
#  Uses parts of code from other update-motd.d files, (C) Dustin Kirkland <kirkland@canonical.com>

# Set variables for the MOTD
URL="https://motd.artemis.org.uk/50"
WAIT=5
CACHE="/var/cache/motd-news.d/50"
[ "$1" = "--force" ] && FORCED=1

# Safely print the MOTD
safe_print() {
        cat "$1" | head -n 10 | tr -d '\000-\011\013\014\016-\037' | cut -c -80
}

# Print from cache if systemd hasn't passed --force
if [ "$FORCED" != "1" ]; then
        if [ -r $CACHE ]; then
                echo
                safe_print $CACHE
        elif [ "$(id -u)" -eq 0 ]; then
                : > $CACHE
        fi
        exit 0
fi

# Set variables for temporary dirs
NEWS=$(mktemp) || exit 1
ERR=$(mktemp) || exit 1

if curl --connect-timeout "$WAIT" --max-time "$WAIT" -Lo- "$URL" >"$NEWS" 2>"$ERR"; then
        echo
        safe_print "$NEWS"
        safe_print "$NEWS" 2>/dev/null >$CACHE || true
else
        : > "$CACHE"
fi
rm -f "$NEWS" "$ERR"
exit 0